package com.hris.common.event;

/**
 * Comprehensive domain event types covering all business domains.
 * Used for structured logging, audit trails, and analytics hooks.
 */
public enum DomainEventType {

    // Leave events
    LEAVE_REQUEST_CREATED,
    LEAVE_REQUEST_SUBMITTED,
    LEAVE_REQUEST_CANCELLED,
    LEAVE_REQUEST_APPROVED,
    LEAVE_REQUEST_REJECTED,
    APPROVAL_STEP_ASSIGNED,
    APPROVAL_STEP_APPROVED,
    APPROVAL_STEP_REJECTED,
    LEAVE_BALANCE_ADJUSTED,
    LEAVE_BALANCE_RESERVED,
    LEAVE_BALANCE_RESERVATION_RELEASED,
    LEAVE_BALANCE_USAGE_CONFIRMED,
    LEAVE_ACCRUAL_APPLIED,

    // Administration request events
    ADMIN_REQUEST_CREATED,
    ADMIN_REQUEST_SUBMITTED,
    ADMIN_REQUEST_IN_REVIEW,
    ADMIN_REQUEST_APPROVED,
    ADMIN_REQUEST_REJECTED,
    ADMIN_REQUEST_COMPLETED,
    ADMIN_REQUEST_CANCELLED,
    ADMIN_REQUEST_COMMENT_ADDED,
    ADMIN_REQUEST_ATTACHMENT_ADDED,
    ADMIN_REQUEST_RESPONSE_ATTACHMENT_ADDED,
    ADMIN_REQUEST_SLA_EXCEEDED,

    // Configuration/security events
    ACCESS_PROFILE_CHANGED,
    USER_PROFILE_ASSIGNMENT_CHANGED,
    VALIDATION_WORKFLOW_CHANGED,
    TEAM_HIERARCHY_CHANGED,
    ACQUISITION_POLICY_CHANGED,
    HR_CALENDAR_CHANGED,
    QUICK_SETTINGS_CHANGED
}
