package com.hris.analytics.enums;

public enum AnalyticsEventType {
    LEAVE_SUBMITTED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_CANCELLED,
    APPROVAL_STEP_APPROVED,
    APPROVAL_STEP_REJECTED,
    EMPLOYEE_HIRED,
    EMPLOYEE_TERMINATED,
    EMPLOYEE_TRANSFERRED,
    PROJECT_ASSIGNMENT_CREATED,
    PROJECT_ASSIGNMENT_ENDED
}
