package com.hris.notification.enums;

public enum NotificationEventType {
    LEAVE_SUBMITTED, LEAVE_APPROVED, LEAVE_REJECTED, LEAVE_CANCELLED,
    LEAVE_BALANCE_ADJUSTED,
    LEAVE_ACCRUAL_APPLIED,
    ADMIN_REQUEST_CREATED,
    ADMIN_REQUEST_SUBMITTED,
    ADMIN_REQUEST_IN_REVIEW,
    ADMIN_REQUEST_APPROVED,
    ADMIN_REQUEST_REJECTED,
    ADMIN_REQUEST_COMPLETED,
    ADMIN_REQUEST_CANCELLED,
    ADMIN_REQUEST_COMMENT_ADDED,
    ADMIN_REQUEST_ATTACHMENT_ADDED,
    ADMIN_REQUEST_RESPONSE_ATTACHMENT_ADDED,
    ADMIN_REQUEST_SLA_EXCEEDED,
    PROJECT_ASSIGNED
}
