package com.hris.access.enums;

public enum StructuralEventType {
    EMPLOYEE_ONBOARDED,
    EMPLOYEE_OFFBOARDED,
    DEPT_HEAD_ASSIGNED,
    DEPT_HEAD_REMOVED,
    TEAM_HEAD_ASSIGNED,
    TEAM_HEAD_REMOVED,
    APPROVER_DESIGNATED,
    APPROVER_REMOVED,
    PROJECT_LEAD_ASSIGNED,
    PROJECT_LEAD_REMOVED
}
