version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: hris_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hris_db
      POSTGRES_USER: hris_user
      POSTGRES_PASSWORD: hris_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hris_user -d hris_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hris_network

  mailpit:
    image: axllent/mailpit:v1.18
    container_name: hris_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - hris_network

volumes:
  postgres_data:

networks:
  hris_network:
    driver: bridge
